spring:
  application:
    name: projeto-spring
  datasource:
    url: jdbc:h2:mem:sdw2024
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true



   
gemini:
  base-url: https://generativelanguage.googleapis.com
  api-key: 